# dashboard.py - stub
# Replace this file with the working one you have locally
def extract_channel_id_from_url(url): ...
def get_channel_metadata(channel_id): ...
def get_recent_videos(channel_id, metadata): ...
def export_to_excel(video_data, metadata): ...
def highlight_top_sponsored_topics(video_data): ...
